using System.Text;
using System.Text.RegularExpressions;
using OneStrokeDemon.ConfigExporter.Diagnostics;
using OneStrokeDemon.ConfigExporter.Model;

namespace OneStrokeDemon.ConfigExporter.Generation;

// 保存一次ConfigIds生成的UTF-8字节及统计信息，供写盘和验证阶段复用。
internal sealed record GeneratedConfigIds(byte[] Bytes, int SetCount, int ConstantCount);

// 描述一个稳定ID分组与其来源工作表字段之间的映射。
internal sealed record ConfigIdSetContract(string ClassName, string SheetName, string FieldName);

// 根据已校验的配置文档确定性生成运行时可引用的ConfigIds常量文件。
internal sealed class ConfigIdsGenerator
{
    private static readonly Regex StableIdPattern = new(
        "^[a-z][a-z0-9_]*$",
        RegexOptions.CultureInvariant | RegexOptions.Compiled);

    private static readonly IReadOnlyList<ConfigIdSetContract> IdSets = new[]
    {
        Set("GlobalKeys", "Global", "key"),
        Set("Players", "Players", "playerId"),
        Set("Stances", "Stances", "stanceId"),
        Set("StrokeRules", "StrokeRules", "ruleId"),
        Set("DamageFormulas", "DamageFormulas", "formulaId"),
        Set("DefenseRules", "DefenseRules", "defenseRuleId"),
        Set("WeakpointRules", "WeakpointRules", "weakpointRuleId"),
        Set("MovePatterns", "MovePatterns", "movePatternId"),
        Set("Enemies", "Enemies", "enemyId"),
        Set("EnemyAttacks", "EnemyAttacks", "attackId"),
        Set("EnemyAttackSets", "EnemyAttacks", "attackSetId"),
        Set("Projectiles", "Projectiles", "projectileId"),
        Set("Buffs", "Buffs", "buffId"),
        Set("Skills", "Skills", "skillId"),
        Set("EffectGroups", "SkillEffects", "effectGroupId"),
        Set("Levels", "Levels", "levelId"),
        Set("Waves", "Waves", "waveId"),
        Set("SpawnPoints", "SpawnPoints", "spawnPointId"),
        Set("EnemyModifiers", "EnemyModifiers", "modifierId"),
        Set("Spawns", "Spawns", "spawnId"),
        Set("BossPhases", "BossPhases", "bossPhaseId"),
        Set("RewardTables", "Rewards", "rewardTableId"),
        Set("Tutorials", "Tutorials", "tutorialId"),
        Set("Texts", "Texts", "textKey"),
        Set("AudioCues", "AudioCues", "audioKey"),
        Set("VfxCues", "VfxCues", "vfxKey"),
        Set("Assets", "AssetManifest", "assetKey"),
        Set("FeedbackCues", "FeedbackCues", "feedbackId"),
    };

    // 读取全部受管ID分组，按稳定顺序输出带中文说明的C#源码。
    public GeneratedConfigIds Generate(ConfigDocument document, string contentHash)
    {
        // 先解析并排序所有分组，后续统计与文本生成共享同一份不可变结果。
        var resolvedSets = IdSets.Select(contract => new
        {
            Contract = contract,
            Values = ReadValues(document, contract),
        }).ToArray();
        var constantCount = resolvedSets.Sum(item => item.Values.Count);
        var builder = new StringBuilder(capacity: Math.Max(4096, constantCount * 72));
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by Tools/ConfigExporter. Do not edit by hand.");
        builder.AppendLine("// 此文件由配置导出器自动生成，请勿手工修改；所有常量均来自已校验的配置表。");
        builder.AppendLine();
        builder.AppendLine("namespace OneStrokeDemon.Config");
        builder.AppendLine("{");
        builder.AppendLine("    // 集中提供配置版本、内容哈希与各表稳定ID，避免产品代码散落字符串字面量。");
        builder.AppendLine("    public static class ConfigIds");
        builder.AppendLine("    {");
        builder.AppendLine("        // 当前配置契约的schema版本。");
        builder.AppendLine($"        public const int SchemaVersion = {document.SchemaVersion};");
        builder.AppendLine("        // 当前配置内容版本。");
        builder.AppendLine($"        public const string ContentVersion = \"{Escape(document.ContentVersion)}\";");
        builder.AppendLine("        // 规范化配置内容的SHA-256哈希。");
        builder.AppendLine($"        public const string ContentHash = \"{Escape(contentHash)}\";");
        builder.AppendLine("        // 本文件包含的稳定ID分组数量。");
        builder.AppendLine($"        public const int IdSetCount = {resolvedSets.Length};");
        builder.AppendLine("        // 本文件包含的稳定ID常量总数。");
        builder.AppendLine($"        public const int IdConstantCount = {constantCount};");

        // 每个分组标明表字段来源，每个常量保留原始稳定ID，便于从代码追溯到配置。
        foreach (var item in resolvedSets)
        {
            builder.AppendLine();
            builder.AppendLine(
                $"        // 汇总来自{item.Contract.SheetName}.{item.Contract.FieldName}的稳定配置ID。");
            builder.AppendLine($"        public static class {item.Contract.ClassName}");
            builder.AppendLine("        {");
            foreach (var value in item.Values)
            {
                builder.AppendLine($"            // 配置ID：{value}。");
                builder.AppendLine(
                    $"            public const string {ToIdentifier(value)} = \"{Escape(value)}\";");
            }

            builder.AppendLine("        }");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        // StringBuilder.AppendLine 跟随宿主平台；编码前归一化，保证生成物跨平台字节一致。
        string source = builder.ToString()
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace("\r", "\n", StringComparison.Ordinal);
        return new GeneratedConfigIds(
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(source),
            resolvedSets.Length,
            constantCount);
    }

    // 从指定表字段提取、去重并按序排列稳定ID，同时拒绝非法值和C#标识符碰撞。
    private static IReadOnlyList<string> ReadValues(
        ConfigDocument document,
        ConfigIdSetContract contract)
    {
        var values = document.GetRequiredTable(contract.SheetName).Rows
            .Select(row => row.GetValue(contract.FieldName) as string)
            .Select(value => value ?? throw Failure(
                $"{contract.SheetName}.{contract.FieldName} contains a non-string or null generated ID."))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(value => value, StringComparer.Ordinal)
            .ToArray();
        var identifiers = new Dictionary<string, string>(StringComparer.Ordinal);
        // 在生成源码前完成全部标识符验证，防止写出部分有效、部分冲突的文件。
        foreach (var value in values)
        {
            if (!StableIdPattern.IsMatch(value))
            {
                throw Failure(
                    $"Generated ID '{value}' from {contract.SheetName}.{contract.FieldName} is not a stable ID.");
            }

            var identifier = ToIdentifier(value);
            if (identifiers.TryGetValue(identifier, out var existing) &&
                !string.Equals(existing, value, StringComparison.Ordinal))
            {
                throw Failure(
                    $"Generated C# identifier collision in {contract.ClassName}: '{existing}' and '{value}' " +
                    $"both map to '{identifier}'.");
            }

            identifiers.Add(identifier, value);
        }

        return values;
    }

    // 将下划线形式的稳定ID转换为PascalCase C#常量名。
    private static string ToIdentifier(string stableId)
    {
        var builder = new StringBuilder(stableId.Length);
        // 每个非空片段首字母大写，其余字符保持稳定ID原貌。
        foreach (var segment in stableId.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            builder.Append(char.ToUpperInvariant(segment[0]));
            if (segment.Length > 1)
            {
                builder.Append(segment.AsSpan(1));
            }
        }

        if (builder.Length == 0)
        {
            throw Failure($"Stable ID '{stableId}' does not produce a C# identifier.");
        }

        return builder.ToString();
    }

    // 转义会破坏C#字符串字面量的字符，保证生成源码始终可编译。
    private static string Escape(string value)
    {
        return value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);
    }

    // 创建一条分组映射，使静态清单保持紧凑且易于审查。
    private static ConfigIdSetContract Set(string className, string sheetName, string fieldName)
    {
        return new ConfigIdSetContract(className, sheetName, fieldName);
    }

    // 统一构造ConfigIds生成阶段的CFG013错误。
    private static ConfigExportException Failure(string message)
    {
        return new ConfigExportException("CFG013", message);
    }
}
