using System.Text;
using System.Text.RegularExpressions;
using OneStrokeDemon.ConfigExporter.Diagnostics;
using OneStrokeDemon.ConfigExporter.Model;

namespace OneStrokeDemon.ConfigExporter.Generation;

internal sealed record GeneratedConfigIds(byte[] Bytes, int SetCount, int ConstantCount);

internal sealed record ConfigIdSetContract(string ClassName, string SheetName, string FieldName);

internal sealed class ConfigIdsGenerator
{
    private static readonly Regex StableIdPattern = new(
        "^[a-z][a-z0-9_]*$",
        RegexOptions.CultureInvariant | RegexOptions.Compiled);

    private static readonly IReadOnlyList<ConfigIdSetContract> IdSets = new[]
    {
        Set("GlobalKeys", "Global", "key"),
        Set("Players", "Players", "playerId"),
        Set("Stances", "Stances", "stanceId"),
        Set("StrokeRules", "StrokeRules", "ruleId"),
        Set("DamageFormulas", "DamageFormulas", "formulaId"),
        Set("DefenseRules", "DefenseRules", "defenseRuleId"),
        Set("WeakpointRules", "WeakpointRules", "weakpointRuleId"),
        Set("MovePatterns", "MovePatterns", "movePatternId"),
        Set("Enemies", "Enemies", "enemyId"),
        Set("EnemyAttacks", "EnemyAttacks", "attackId"),
        Set("EnemyAttackSets", "EnemyAttacks", "attackSetId"),
        Set("Projectiles", "Projectiles", "projectileId"),
        Set("Buffs", "Buffs", "buffId"),
        Set("Skills", "Skills", "skillId"),
        Set("EffectGroups", "SkillEffects", "effectGroupId"),
        Set("Levels", "Levels", "levelId"),
        Set("Waves", "Waves", "waveId"),
        Set("SpawnPoints", "SpawnPoints", "spawnPointId"),
        Set("EnemyModifiers", "EnemyModifiers", "modifierId"),
        Set("Spawns", "Spawns", "spawnId"),
        Set("BossPhases", "BossPhases", "bossPhaseId"),
        Set("RewardTables", "Rewards", "rewardTableId"),
        Set("Tutorials", "Tutorials", "tutorialId"),
        Set("Texts", "Texts", "textKey"),
        Set("AudioCues", "AudioCues", "audioKey"),
        Set("VfxCues", "VfxCues", "vfxKey"),
        Set("Assets", "AssetManifest", "assetKey"),
        Set("FeedbackCues", "FeedbackCues", "feedbackId"),
    };

    public GeneratedConfigIds Generate(ConfigDocument document, string contentHash)
    {
        var resolvedSets = IdSets.Select(contract => new
        {
            Contract = contract,
            Values = ReadValues(document, contract),
        }).ToArray();
        var constantCount = resolvedSets.Sum(item => item.Values.Count);
        var builder = new StringBuilder(capacity: Math.Max(4096, constantCount * 72));
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by Tools/ConfigExporter. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("namespace OneStrokeDemon.Config");
        builder.AppendLine("{");
        builder.AppendLine("    public static class ConfigIds");
        builder.AppendLine("    {");
        builder.AppendLine($"        public const int SchemaVersion = {document.SchemaVersion};");
        builder.AppendLine($"        public const string ContentVersion = \"{Escape(document.ContentVersion)}\";");
        builder.AppendLine($"        public const string ContentHash = \"{Escape(contentHash)}\";");
        builder.AppendLine($"        public const int IdSetCount = {resolvedSets.Length};");
        builder.AppendLine($"        public const int IdConstantCount = {constantCount};");

        foreach (var item in resolvedSets)
        {
            builder.AppendLine();
            builder.AppendLine($"        public static class {item.Contract.ClassName}");
            builder.AppendLine("        {");
            foreach (var value in item.Values)
            {
                builder.AppendLine(
                    $"            public const string {ToIdentifier(value)} = \"{Escape(value)}\";");
            }

            builder.AppendLine("        }");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return new GeneratedConfigIds(
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(builder.ToString()),
            resolvedSets.Length,
            constantCount);
    }

    private static IReadOnlyList<string> ReadValues(
        ConfigDocument document,
        ConfigIdSetContract contract)
    {
        var values = document.GetRequiredTable(contract.SheetName).Rows
            .Select(row => row.GetValue(contract.FieldName) as string)
            .Select(value => value ?? throw Failure(
                $"{contract.SheetName}.{contract.FieldName} contains a non-string or null generated ID."))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(value => value, StringComparer.Ordinal)
            .ToArray();
        var identifiers = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var value in values)
        {
            if (!StableIdPattern.IsMatch(value))
            {
                throw Failure(
                    $"Generated ID '{value}' from {contract.SheetName}.{contract.FieldName} is not a stable ID.");
            }

            var identifier = ToIdentifier(value);
            if (identifiers.TryGetValue(identifier, out var existing) &&
                !string.Equals(existing, value, StringComparison.Ordinal))
            {
                throw Failure(
                    $"Generated C# identifier collision in {contract.ClassName}: '{existing}' and '{value}' " +
                    $"both map to '{identifier}'.");
            }

            identifiers.Add(identifier, value);
        }

        return values;
    }

    private static string ToIdentifier(string stableId)
    {
        var builder = new StringBuilder(stableId.Length);
        foreach (var segment in stableId.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            builder.Append(char.ToUpperInvariant(segment[0]));
            if (segment.Length > 1)
            {
                builder.Append(segment.AsSpan(1));
            }
        }

        if (builder.Length == 0)
        {
            throw Failure($"Stable ID '{stableId}' does not produce a C# identifier.");
        }

        return builder.ToString();
    }

    private static string Escape(string value)
    {
        return value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);
    }

    private static ConfigIdSetContract Set(string className, string sheetName, string fieldName)
    {
        return new ConfigIdSetContract(className, sheetName, fieldName);
    }

    private static ConfigExportException Failure(string message)
    {
        return new ConfigExportException("CFG013", message);
    }
}
